default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: kaizen_development

test:
  <<: *default
  database: kaizen_test

production:
  <<: *default
  database: kaizen_production
  username: kaizen
  password: <%= ENV['KAIZEN_DATABASE_PASSWORD'] %>
